#!/bin/sh

mkdir -p opk
cp ./OpenJazz opk/OpenJazz
cp ./unix/OpenJazz_32x32.png opk/icon.png
cp ./openjazz.000 opk/openjazz.000
cp ./COPYING opk/COPYING

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=OpenJazz
Comment=Jazz jackrabbit engine
Exec=run.sh %f
Icon=icon
Terminal=false
Type=Application
Categories=games;
X-OD-NeedsDownscaling=true' > opk/default."$1".desktop

print '#!/bin/sh
SOURCE="$1"
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
./OpenJazz "$DIR"' > opk/run.sh

chmod a+x opk/run.sh

mksquashfs ./opk OpenJazz_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
